# Generated by Django 4.2.3 on 2023-07-31 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
