# Generated by Django 4.2.3 on 2023-07-31 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='name',
            new_name='description',
        ),
    ]
