# Generated by Django 4.2.3 on 2023-08-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0005_todo_is_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moodtracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
    ]
