# Generated by Django 4.2.3 on 2023-08-17 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0005_todo_is_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cares', models.CharField(choices=[('wa', 'Walking'), ('me', 'Meditate'), ('ba', 'Bath'), ('co', 'Cook'), ('ex', 'Exercise')], default=None, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Feeling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feels', models.CharField(choices=[('ha', 'Happy'), ('jo', 'Joyful'), ('co', 'Content'), ('re', 'Relaxed'), ('lo', 'Loved'), ('va', 'Valued')], default=None, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='MoodTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('emote', models.FileField(blank=True, null=True, upload_to='')),
                ('care', models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, to='sample.caring')),
                ('feeling', models.ForeignKey(blank=True, null=True, on_delete=models.CASCADE, to='sample.feeling')),
            ],
        ),
    ]
