# Generated by Django 4.2.3 on 2023-08-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0006_moodtracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodtracker',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
