# Generated by Django 4.2.3 on 2023-08-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0012_rename_mood_moodtracker_mood_am_moodtracker_mood_pm'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodtracker',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
