# Generated by Django 4.2.3 on 2023-08-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0013_moodtracker_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='moodtracker',
            name='feeling',
            field=models.ManyToManyField(to='sample.feeling'),
        ),
    ]
