# Generated by Django 4.2.3 on 2023-08-16 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0014_feeling_moodtracker_feeling'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moodtracker',
            old_name='feeling',
            new_name='feelings',
        ),
    ]
