# Generated by Django 4.2.3 on 2023-08-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0015_rename_feeling_moodtracker_feelings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Care',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habits', models.CharField(max_length=30)),
                ('enough', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='moodtracker',
            name='feelings',
            field=models.ManyToManyField(blank=True, to='sample.feeling'),
        ),
        migrations.AddField(
            model_name='moodtracker',
            name='cares',
            field=models.ManyToManyField(blank=True, to='sample.care'),
        ),
    ]
