# Generated by Django 4.2.3 on 2023-08-30 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0016_care_alter_moodtracker_feelings_moodtracker_cares'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='is_done',
        ),
    ]
