# Generated by Django 4.2.3 on 2023-09-04 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0018_moodtracker_what_didnt_work_moodtracker_what_worked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moodtracker',
            old_name='What_didnt_work',
            new_name='what_didnt_work',
        ),
    ]
