# Generated by Django 4.2.3 on 2023-09-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0019_rename_what_didnt_work_moodtracker_what_didnt_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodtracker',
            name='stress',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
