# Generated by Django 4.2.3 on 2023-09-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0026_alter_moodtracker_stress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodtracker',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
