# Generated by Django 4.2.3 on 2023-09-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0027_alter_moodtracker_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='care',
            name='enough',
        ),
        migrations.AddField(
            model_name='moodtracker',
            name='did_enough',
            field=models.ManyToManyField(blank=True, to='sample.enough'),
        ),
    ]
